services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cid
      POSTGRES_PASSWORD: cid
      POSTGRES_DB: cid
    ports:
      - "5432:5432"
    volumes:
      - cid-pg:/var/lib/postgresql/data

volumes:
  cid-pg:
